### PR TITLE
Yarn

### PR DESCRIPTION
**Pull request by screendriver**
1. Added [Yarn](https://yarnpkg.com) for dependency installation
2. Removed `.jsx` file extension from `import` statements

### CODE REVIEW

**Comment by nshntarora** [comment]
Hey @screendriver, It'd be great if you could also put in a case in favor of `Yarn`. Why shouldn't we stick to `npm`?

**Comment by krishnagopinath** [comment]
I like yarn over npm because 

* It's easier to keep a lockdown on version numbers. With npm, there is no guarantee that the same package.json will install the same versions of the dependencies in any machine it is run on. You could lock all of it down with something called `npm shrinkwrap` but it's not automatic. Yarn introduces a `lock` file that updates everytime a module is added. This makes the installation of packages in every machine deterministic automatically, which cannot be guaranteed in the case of `npm`. 

* The messages seem clearer and nicer, when compared to npm

**Comment by krishnagopinath** [comment]
That said, it's not an absolutely essential thing for an immediate jump to yarn. Chances are that, by the time we need this, npm might catch up with yarn in the feature set 😀

**Comment by screendriver** [comment]
Everything said :wink: With yarn your package installation is 100% reproducible on **every** machine.

**Comment by krishnagopinath** [comment]
We are in the midst of a major refactor and we'd probably stick to npm5 atm. So, closing this PR. 😢

**Pull request closed without merging**
