### PR TITLE
add e2e tests (close #28)

### LINKED ISSUE #28: e2e tests
Matterwiki is a complex application.
I propose to write e2e tests and setup CI on `travis` or `appveyor`.
I can do this using [testcafe](https://github.com/DevExpress/testcafe).
What do you think about it?

### PR DESCRIPTION
**Pull request by miherlosev**
The project owner should setup Travis for this repository as described in [this article](https://devexpress.github.io/testcafe/documentation/recipes/running-tests-in-firefox-and-chrome-using-travis-ci.html)

Tests will run in the latest Google Chrome version.

Changes:
- added a test user in `db/matterwiki.sqlite`
- added the first test set that covers creating an article

### CODE REVIEW

**Comment by miherlosev** [comment]
I've fixed tests.

**Comment by nshntarora** [comment]
Great! Thanks a lot of this :smile: 

We could only run away from writing tests for so long.

Questions:
The test user is persistent in the database, right?
The test user has the ID of `1`, which as of now, is the how we identify the admin. The admin has the ID `1`.
I don't want all installations to have the test user by default.
Instead of adding the test user by default to the database. Can we add that in the documentation, that is you want to run tests you will have to create a test user first. How would such a system work with Travis?

To be honest, it's the first time I'm integrating tests with a project. I could use all the help I could get.

**Comment by AlexanderMoskovkin** [comment]
@nshntarora we are ready to provide any help with TestCafe =)

I believe that the best way is to use a separate db for tests. Take a look at my PR to @miherlosev 's branch: https://github.com/miherlosev/Matterwiki/pull/1/files

I've added `TESTING` env variable. If it is set the application uses `tests/e2e/db/matterwiki.sqlite`.
So, in this case it's possible that there are no a registered user when tests are started, so I've added some additional logic to the `login` function: https://github.com/miherlosev/Matterwiki/pull/1/files#diff-1219fe7385f85e76c06112d5bafc6594R69

If you like this approach, @miherlosev can add this changes to his pull request.

Also, I've created a screencast to show how you can run the tests during development: [https://www.screencast.com/t/Cv7q37DSN7](https://www.screencast.com/t/Cv7q37DSN7). I've shown two ways: via CLI and via [Visual Studio Code TestCafe plugin](https://marketplace.visualstudio.com/items?itemName=romanresh.testcafe-test-runner)

**Comment by nshntarora** [comment]
Thankyou @AlexanderMoskovkin :smile: this works great!

@miherlosev could you please make the required changes?

**Comment by nshntarora** [comment]
Hi! The test is failing because there is no `db` folder inside `tests/e2e`

Can you please add that, and also an empty `.gitignore` inside the `db` folder to prevent tracking issues :smile:

**Comment by miherlosev** [comment]
Done. You can review this

**Comment by nshntarora** [comment]
Merged. Thanks a lot :smile: 
Also tried writing a basic test of my own. Great library! Good Job :+1:

**Comment by AlexanderMoskovkin** [comment]
🎉🎉🎉 You have e2e tests now :smile:
If you need any assistance feel free to contact us via [issues](https://github.com/DevExpress/testcafe/issues), [forum](https://testcafe-discuss.devexpress.com/) or on [stackoverflow](http://stackoverflow.com/questions/tagged/testcafe)

**Pull request merged**
