### PR TITLE
Add support for docker

### PR DESCRIPTION
**Pull request by chrisDeFouRire**
Here's a Dockerfile _(and documentation)_ for running Matterwiki in a docker container.

I hope it will help people try Matterwiki.

### CODE REVIEW

**Comment by Agezao** [comment]
Probably a duplicate of: https://github.com/Matterwiki/Matterwiki/pull/22

**Comment by chrisDeFouRire** [comment]
except this one works if your node_modules isn't empty...

**Comment by nshntarora** [comment]
Hey! @chrisDeFouRire  one of your commits in this pull request all fixes the fetchPolyfill issue, which has been fixed in another one of your later pull requests.
Please update it, and remove the `fetch` related commits.

**Comment by chrisDeFouRire** [comment]
I'm submitting a cleaner pull request

**Pull request closed without merging**
