### PR TITLE
Moving from trix to draft

### PR DESCRIPTION
**Pull request by krishnagopinath**
This PR tries to begin the effort to move to a more robust editor by switching to [draft](https://facebook.github.io/draft-js/). 

This would be open to customization, such as #18, #15, #30 and more.

(From next time, lets maintain an issue and create multiple PRs. Reviewing something like this could be a nightmare, I'm sure)

### CODE REVIEW

**Comment by krishnagopinath** [comment]
Can this be closed, @nshntarora ?

**Comment by nshntarora** [comment]
@krishnagopinath Yes, Can you please change the target to the `v0.3.0` branch?

**Comment by krishnagopinath** [comment]
Apparently it looks like you've already merged all these commits 😄

So this can just be closed, I believe

**Comment by nshntarora** [comment]
Oh yeah, my bad :stuck_out_tongue_closed_eyes:

**Pull request closed without merging**
