### PR TITLE
Server refactor, new directory structure and more!

### PR DESCRIPTION
**Pull request by krishnagopinath**
There's too much to describe here. I'll try my best to describe what's going on:

* Moves server stuff into src/server
* We use Node 8 for everything now, so we've got fun stuff like `async` and `await`! 🎉 
* Makes migration and seed script stuff into a CLI task than mucking it up with code
* New directory structure for the server:

```
.
├── app.js
├── middleware
│   ├── bodyParser.js
│   ├── checkAuth.js
│   ├── checkRole.js
│   └── upload.js
├── models
│   ├── archive.js
│   ├── article.js
│   ├── topic.js
│   └── user.js
├── routes
│   ├── articles.js
│   ├── auth.js
│   ├── search.js
│   ├── setup.js
│   ├── topics.js
│   ├── uploads.js
│   └── users.js
├── server.js
└── utils
    ├── WDSStarter.js
    ├── buildDbModel.js
    ├── config.js
    ├── constants.js
    └── db.js
```

* Each file in routes could be its own thing, cos each of those make their own sub-routers
* app.js handles app-specific stuff
* server.js handles bootstrapping the server, webpack-dev-server and config management
* Adds new way to handle config via a `config.env` file, which is used for DB and other credentials
* We support ONLY MySQL from this point, which means Bye bye SQLITE!

## TODO:

* Update README
* Comments in the code, among other things

## SETUP

@nshntarora if you want to test this, here's a gist of what you have to do (Since we don't have the README updated yet): 

* Of course, you'd have to setup MySQL
* Make a `config.env` file at the root and paste this in:

```
DB_HOST=localhost
DB_NAME=<Fill>
DB_PASSWORD=<Fill>
DB_USER_NAME=<Fill>
NODE_ENV=development
SERVER_PORT=5000
SERVER_HOST=localhost
AUTH_SECRET=thisisasecretkeyforjwtauth
```

The stuff that say `<Fill>`, you'll need to fill.  
* Remove the `node_modules` dir.
* Install node 8. Use `nvm`, if you can.
* `npm i`
* Now, run the migration CLI:
```
npm run db:migrate
```
* Then, the seed scripts:
```
npm run db:seed
```
* After this, the regular `npm run dev` should start stuff as usual. 

I see this becoming a nice install script in the future, but that's a TODO we'll get to later.

### CODE REVIEW

**Comment by krishnagopinath** [comment]
I believe this is done. Test it and tell me if everything seems to work @nshntarora.

**Comment by nshntarora** [comment]
@krishnagopinath 

When I'm trying to delete an article that has an article in the archives table, I'm getting the following error.

```
delete from `articles` where `id` = '1' - ER_ROW_IS_REFERENCED_2: Cannot delete or update a parent row: a foreign key constraint fails (`matterwiki_development`.`archives`, CONSTRAINT `archives_article_id_foreign` FOREIGN KEY (`article_id`) REFERENCES `articles` (`id`))
```

Probably should delete all the archives before we try and delete the article.

**Comment by nshntarora** [comment]
@krishnagopinath Also, similar issue pops up when I try to delete a topic that has an article linked to it.
Let's follow this flow for topic deletion:

When seeding let's create a topic called `uncategorised`, then if a topic is deleted, we move all of its articles to the uncategorised topic.

**Review by nshntarora — CHANGES_REQUESTED** [review]
.

**Pull request closed without merging**
